[2024-11-09T13:49:49.296+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-09T13:49:49.320+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_postgres manual__2024-11-09T13:49:43.110973+00:00 [queued]>
[2024-11-09T13:49:49.329+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_postgres manual__2024-11-09T13:49:43.110973+00:00 [queued]>
[2024-11-09T13:49:49.332+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-09T13:49:49.348+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_data_from_postgres> on 2024-11-09 13:49:43.110973+00:00
[2024-11-09T13:49:49.352+0000] {standard_task_runner.py:64} INFO - Started process 198 to run task
[2024-11-09T13:49:49.355+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'fetch_data_from_postgres', 'manual__2024-11-09T13:49:43.110973+00:00', '--job-id', '297', '--raw', '--subdir', 'DAGS_FOLDER/pipline.py', '--cfg-path', '/tmp/tmp1ow7sduj']
[2024-11-09T13:49:49.357+0000] {standard_task_runner.py:91} INFO - Job 297: Subtask fetch_data_from_postgres
[2024-11-09T13:49:49.399+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.fetch_data_from_postgres manual__2024-11-09T13:49:43.110973+00:00 [running]> on host 3f94ec02a752
[2024-11-09T13:49:49.482+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_from_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-09T13:49:43.110973+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-09T13:49:43.110973+00:00'
[2024-11-09T13:49:49.483+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-09T13:49:49.491+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-11-09T13:49:51.534+0000] {logging_mixin.py:188} INFO - Error connecting to PostgreSQL: connection to server at "host.docker.internal" (192.168.65.254), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-09T13:49:51.535+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-09T13:49:51.536+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-09T13:49:51.546+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=fetch_data_from_postgres, run_id=manual__2024-11-09T13:49:43.110973+00:00, execution_date=20241109T134943, start_date=20241109T134949, end_date=20241109T134951
[2024-11-09T13:49:51.575+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-09T13:49:51.596+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-09T13:49:51.598+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
