[2024-11-10T01:49:20.595+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-10T01:49:20.618+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_postgres manual__2024-11-10T01:49:11.910303+00:00 [queued]>
[2024-11-10T01:49:20.626+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_postgres manual__2024-11-10T01:49:11.910303+00:00 [queued]>
[2024-11-10T01:49:20.629+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-10T01:49:20.640+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_data_from_postgres> on 2024-11-10 01:49:11.910303+00:00
[2024-11-10T01:49:20.643+0000] {standard_task_runner.py:64} INFO - Started process 242 to run task
[2024-11-10T01:49:20.645+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'fetch_data_from_postgres', 'manual__2024-11-10T01:49:11.910303+00:00', '--job-id', '447', '--raw', '--subdir', 'DAGS_FOLDER/pipline.py', '--cfg-path', '/tmp/tmpbveshxgy']
[2024-11-10T01:49:20.648+0000] {standard_task_runner.py:91} INFO - Job 447: Subtask fetch_data_from_postgres
[2024-11-10T01:49:20.688+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.fetch_data_from_postgres manual__2024-11-10T01:49:11.910303+00:00 [running]> on host f27d990d3764
[2024-11-10T01:49:20.765+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_from_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-10T01:49:11.910303+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-10T01:49:11.910303+00:00'
[2024-11-10T01:49:20.767+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-10T01:49:20.775+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-11-10T01:49:22.818+0000] {logging_mixin.py:188} INFO - Error connecting to PostgreSQL: connection to server at "host.docker.internal" (192.168.65.254), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-10T01:49:22.819+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-10T01:49:22.820+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-10T01:49:22.827+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=fetch_data_from_postgres, run_id=manual__2024-11-10T01:49:11.910303+00:00, execution_date=20241110T014911, start_date=20241110T014920, end_date=20241110T014922
[2024-11-10T01:49:22.868+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-10T01:49:22.888+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-10T01:49:22.892+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
