[2024-11-09T19:02:36.177+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-09T19:02:36.291+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_postgres manual__2024-11-09T19:02:26.264680+00:00 [queued]>
[2024-11-09T19:02:36.332+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.fetch_data_from_postgres manual__2024-11-09T19:02:26.264680+00:00 [queued]>
[2024-11-09T19:02:36.354+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-09T19:02:36.414+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_data_from_postgres> on 2024-11-09 19:02:26.264680+00:00
[2024-11-09T19:02:36.429+0000] {standard_task_runner.py:64} INFO - Started process 730 to run task
[2024-11-09T19:02:36.442+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'fetch_data_from_postgres', 'manual__2024-11-09T19:02:26.264680+00:00', '--job-id', '425', '--raw', '--subdir', 'DAGS_FOLDER/pipline.py', '--cfg-path', '/tmp/tmpj5vg8e6n']
[2024-11-09T19:02:36.451+0000] {standard_task_runner.py:91} INFO - Job 425: Subtask fetch_data_from_postgres
[2024-11-09T19:02:36.627+0000] {task_command.py:426} INFO - Running <TaskInstance: pipeline.fetch_data_from_postgres manual__2024-11-09T19:02:26.264680+00:00 [running]> on host 720c13b76b76
[2024-11-09T19:02:37.006+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_from_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-09T19:02:26.264680+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-09T19:02:26.264680+00:00'
[2024-11-09T19:02:37.011+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-09T19:02:37.042+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-11-09T19:02:39.107+0000] {logging_mixin.py:188} INFO - Error connecting to PostgreSQL: connection to server at "host.docker.internal" (192.168.65.254), port 5433 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-09T19:02:39.109+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-09T19:02:39.111+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-09T19:02:39.146+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=fetch_data_from_postgres, run_id=manual__2024-11-09T19:02:26.264680+00:00, execution_date=20241109T190226, start_date=20241109T190236, end_date=20241109T190239
[2024-11-09T19:02:39.234+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-09T19:02:39.343+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-09T19:02:39.354+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
